// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: pb/api_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *AuthGetOneRequest) Reset() {
	*x = AuthGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGetOneRequest) ProtoMessage() {}

func (x *AuthGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGetOneRequest.ProtoReflect.Descriptor instead.
func (*AuthGetOneRequest) Descriptor() ([]byte, []int) {
	return file_pb_api_data_proto_rawDescGZIP(), []int{0}
}

func (x *AuthGetOneRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type AuthGetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret   string `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	DeveloperId string `protobuf:"bytes,3,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	CreatTime   int64  `protobuf:"varint,4,opt,name=creat_time,json=creatTime,proto3" json:"creat_time,omitempty"`
}

func (x *AuthGetOneResponse) Reset() {
	*x = AuthGetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthGetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGetOneResponse) ProtoMessage() {}

func (x *AuthGetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGetOneResponse.ProtoReflect.Descriptor instead.
func (*AuthGetOneResponse) Descriptor() ([]byte, []int) {
	return file_pb_api_data_proto_rawDescGZIP(), []int{1}
}

func (x *AuthGetOneResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AuthGetOneResponse) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *AuthGetOneResponse) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *AuthGetOneResponse) GetCreatTime() int64 {
	if x != nil {
		return x.CreatTime
	}
	return 0
}

type AllowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestKey string `protobuf:"bytes,1,opt,name=requestKey,proto3" json:"requestKey,omitempty"`
	Rate       int32  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Burst      int32  `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_pb_api_data_proto_rawDescGZIP(), []int{2}
}

func (x *AllowRequest) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *AllowRequest) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *AllowRequest) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type AllowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAllow bool `protobuf:"varint,1,opt,name=is_allow,json=isAllow,proto3" json:"is_allow,omitempty"`
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_pb_api_data_proto_rawDescGZIP(), []int{3}
}

func (x *AllowResponse) GetIsAllow() bool {
	if x != nil {
		return x.IsAllow
	}
	return false
}

var File_pb_api_data_proto protoreflect.FileDescriptor

var file_pb_api_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2a, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x58, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x72, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x75, 0x72, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x32, 0x7b, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x61, 0x70, 0x69, 0x5f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_api_data_proto_rawDescOnce sync.Once
	file_pb_api_data_proto_rawDescData = file_pb_api_data_proto_rawDesc
)

func file_pb_api_data_proto_rawDescGZIP() []byte {
	file_pb_api_data_proto_rawDescOnce.Do(func() {
		file_pb_api_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_api_data_proto_rawDescData)
	})
	return file_pb_api_data_proto_rawDescData
}

var file_pb_api_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_api_data_proto_goTypes = []interface{}{
	(*AuthGetOneRequest)(nil),  // 0: pb.AuthGetOneRequest
	(*AuthGetOneResponse)(nil), // 1: pb.AuthGetOneResponse
	(*AllowRequest)(nil),       // 2: pb.AllowRequest
	(*AllowResponse)(nil),      // 3: pb.AllowResponse
}
var file_pb_api_data_proto_depIdxs = []int32{
	0, // 0: pb.ApiData.AuthGetOne:input_type -> pb.AuthGetOneRequest
	2, // 1: pb.ApiData.LimiterAllow:input_type -> pb.AllowRequest
	1, // 2: pb.ApiData.AuthGetOne:output_type -> pb.AuthGetOneResponse
	3, // 3: pb.ApiData.LimiterAllow:output_type -> pb.AllowResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_api_data_proto_init() }
func file_pb_api_data_proto_init() {
	if File_pb_api_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_api_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthGetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_api_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_api_data_proto_goTypes,
		DependencyIndexes: file_pb_api_data_proto_depIdxs,
		MessageInfos:      file_pb_api_data_proto_msgTypes,
	}.Build()
	File_pb_api_data_proto = out.File
	file_pb_api_data_proto_rawDesc = nil
	file_pb_api_data_proto_goTypes = nil
	file_pb_api_data_proto_depIdxs = nil
}
